#!/bin/sh
ManKalah="../external/ManKalah.jar"
MKAgent="java -jar ../build/MKAgent.jar"
MKRefAgent="java -jar /opt/info/courses/COMP34120/Project1_2014/Group2Agent.jar"


read -p "Who goes first? (MKAgent/MKRefAgent)=" firstAgent

case $firstAgent in
  MKAgent ) java -jar $ManKalah "$MKAgent" "$MKRefAgent"; break;;
  MKRefAgent ) java -jar $ManKalah "$MKRefAgent" "$MKAgent"; break;;
  * ) echo "Please answer MKAgent or MKRefAgent";;
esac
